### ISSUE TITLE
question about the function in class PubsSolver : getenergy()

### ISSUE THREAD

**Issue by watersir** [nevillegrech/llvm-energy#1]
Hello author,^-^ thank you very much for your code.But I still don't understand some thing...
 I want to know why the energy consumption calculation of each instruction is calculated in that way, and why there is no separate energy consumption calculation of multiplication instruction? The values of op and prev are always the same, so  the first case: "if op =='add'and prev =='mul' " will not occur?

**Comment by nevillegrech** [comment]
I think you're referring to the energy definitions of the ARM processor. We categorized the instructions into various categories:
* arithmetic
* phi (i.e. copy)
* branching
* memory
* division (special case)
And we assigned weights based after experimenting with some regression models on actual code run on actual hardware.

The special case `if op =='add'and prev =='mul' ` is so because in the generated machine code, those two subsequent instructions are replaced with an "addmul" instruction.

**Comment by watersir** [comment]
Thank you so much~
